# Generated by Django 6.1.1 on 2026-09-11 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال شمسی')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ شارژ ماهیانه (تومان)')),
            ],
            options={
                'verbose_name': 'تعرفه شارژ',
                'verbose_name_plural': 'تعرفه\u200cهای شارژ',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_plan_year_month')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال شمسی')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه')),
                ('payer_kind', models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستاجر')], max_length=10, verbose_name='پرداخت\u200cکننده')),
                ('payer_name', models.CharField(max_length=100, verbose_name='نام پرداخت\u200cکننده')),
                ('paid_at', models.DateField(verbose_name='تاریخ پرداخت')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('kind', models.CharField(choices=[('charge', 'شارژ ماهیانه'), ('other', 'درآمد متفرقه')], default='charge', max_length=10, verbose_name='نوع پرداخت')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='توضیح')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='units.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-paid_at'],
            },
        ),
    ]
