# Generated by Django 6.1.1 on 2026-09-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان درآمد')),
                ('is_charge', models.BooleanField(default=False, help_text='فقط یک نوع درآمد می\u200cتواند شارژ ماهیانه باشد.', verbose_name='شارژ ماهیانه است')),
            ],
            options={
                'verbose_name': 'نوع درآمد',
                'verbose_name_plural': 'انواع درآمد',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='charges.incometype', verbose_name='نوع درآمد'),
        ),
    ]
