# Generated by Django 6.1.1 on 2026-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0004_chargeplan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_kind',
            field=models.CharField(blank=True, choices=[('owner', 'مالک'), ('tenant', 'مستاجر')], default='', max_length=10, verbose_name='پرداخت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام پرداخت\u200cکننده'),
        ),
    ]
