# Generated by Django 6.1.1 on 2026-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0005_alter_payment_payer_kind_alter_payment_payer_name'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'charge')), fields=('unit', 'year', 'month'), name='unique_charge_payment_per_unit_month'),
        ),
    ]
