# Generated by Django 6.1.1 on 2026-10-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0007_incometype_code_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargeplan',
            options={'ordering': ['unit__number', 'year', 'start_month', 'end_month'], 'verbose_name': 'تعرفه شارژ', 'verbose_name_plural': 'تعرفه\u200cهای شارژ'},
        ),
    ]
