# Generated by Django 6.1.1 on 2026-10-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0008_alter_chargeplan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometype',
            name='description',
        ),
    ]
