# Generated by Django 6.1.1 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0009_remove_incometype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
