# Generated by Django 6.1.1 on 2026-10-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0010_alter_payment_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['year', 'month', 'unit__number'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
    ]
