# Generated by Django 6.1.1 on 2026-10-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0011_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='توضیحات'),
        ),
    ]
