# Generated by Django 6.1.1 on 2026-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0012_incometype_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['income_type__code', 'year', 'month', 'unit__number'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
    ]
