# Generated by Django 6.1.1 on 2026-09-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('requires_bill_ids', models.BooleanField(default=False, help_text='برای دسته\u200cهای قبض (آب، گاز، برق) فعال کنید.', verbose_name='شناسه قبض/پرداخت اجباری است')),
            ],
            options={
                'verbose_name': 'نوع مخارج',
                'verbose_name_plural': 'انواع مخارج',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_at', models.DateField(verbose_name='تاریخ هزینه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('bill_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه قبض')),
                ('payment_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه پرداخت')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='فاکتور')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='نوع مخارج')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'مخارج',
                'ordering': ['-spent_at'],
            },
        ),
    ]
