# Generated by Django 6.1.1 on 2026-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_code_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='requires_bill_ids',
            field=models.BooleanField(default=False, help_text='برای دسته\u200cهای قبض (آب، گاز، برق) فعال کنید.', verbose_name='هزینه از نوع قبض است'),
        ),
    ]
