# Generated by Django 6.1.1 on 2026-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensecategory_requires_bill_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان هزینه'),
        ),
    ]
