# Generated by Django 6.1.1 on 2026-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expensecategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spent_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ هزینه'),
        ),
    ]
