# Generated by Django 6.1.1 on 2026-10-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_spent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['spent_at', 'id'], 'verbose_name': 'هزینه', 'verbose_name_plural': 'مخارج'},
        ),
    ]
