# Generated by Django 6.1.1 on 2026-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='شرح'),
        ),
    ]
