# Generated by Django 6.1.1 on 2026-09-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره واحد')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='موبایل مالک')),
                ('tenant_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام مستاجر')),
                ('tenant_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='موبایل مستاجر')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ورود')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TenancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مستاجر')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل مستاجر')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='units.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'سابقه سکونت',
                'verbose_name_plural': 'سوابق سکونت',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل مالک')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='units.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'سابقه مالکیت',
                'verbose_name_plural': 'سوابق مالکیت',
                'ordering': ['-start_date'],
            },
        ),
    ]
